//! Reading and writing the general pasteboard through AppKit directly.
//!
//! `arboard` is deliberately not used: it exposes no `changeCount`, it
//! re-encodes GIFs to PNG (destroying animation), and it cannot write file
//! objects so a copied file would paste as a path string instead of a file.

use objc2_app_kit::{
    NSPasteboard, NSPasteboardTypeFileURL, NSPasteboardTypeHTML, NSPasteboardTypePNG,
    NSPasteboardTypeRTF, NSPasteboardTypeString, NSPasteboardTypeTIFF,
};
use objc2_foundation::{NSArray, NSData, NSString};

use crate::types::Captured;

/// Pasteboard types that mean "do not record this".
///
/// Password managers and any app that marks content as secret declare these;
/// checking them happens before a single payload byte is read.
/// See <https://nspasteboard.org>.
const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// Legacy Finder type holding an array of every selected path.
const NS_FILENAMES_PBOARD_TYPE: &str = "NSFilenamesPboardType";

fn pasteboard() -> objc2::rc::Retained<NSPasteboard> {
    unsafe { NSPasteboard::generalPasteboard() }
}

/// The pasteboard write counter. Increments on every write by any process.
pub fn change_count() -> i64 {
    let count = NSPasteboard::changeCount(&pasteboard());
    // `changeCount` is an `NSInteger`, which maps to `isize`.
    count as i64
}

fn type_names() -> Vec<String> {
    let pb = pasteboard();
    let Some(types) = (unsafe { pb.types() }) else {
        return Vec::new();
    };
    let mut out = Vec::with_capacity(types.count());
    for i in 0..types.count() {
        let t = types.objectAtIndex(i);
        out.push(t.to_string());
    }
    out
}

fn has_concealed_type(names: &[String]) -> bool {
    names
        .iter()
        .any(|t| CONCEALED_TYPES.iter().any(|c| t == c))
}

fn read_string(paste_type: &objc2_foundation::NSString) -> Option<String> {
    let pb = pasteboard();
    unsafe { pb.stringForType(paste_type) }.map(|s| s.to_string())
}

fn read_data(paste_type: &objc2_foundation::NSString) -> Option<Vec<u8>> {
    let pb = pasteboard();
    unsafe { pb.dataForType(paste_type) }.map(|d| d.to_vec())
}

/// Read whatever is on the pasteboard right now, classified and filtered.
///
/// Returns `Captured::Skip` for anything empty, concealed, or unsupported.
pub fn read_current() -> Captured {
    let names = type_names();
    if names.is_empty() || has_concealed_type(&names) {
        return Captured::Skip;
    }

    // Files win over text: a Finder copy also carries a path string, and
    // pasting that string is far less useful than pasting the file itself.
    if let Some(files) = read_file_urls(&names) {
        return Captured::Files { paths: files };
    }

    if let Some(image) = read_image(&names) {
        return image;
    }

    if let Some(text) = read_string(unsafe { NSPasteboardTypeString }) {
        if text.trim().is_empty() {
            return Captured::Skip;
        }
        let html = read_string(unsafe { NSPasteboardTypeHTML });
        let rtf = read_data(unsafe { NSPasteboardTypeRTF });
        return Captured::Text { text, html, rtf };
    }

    Captured::Skip
}

fn read_file_urls(names: &[String]) -> Option<Vec<String>> {
    let has_legacy = names.iter().any(|t| t == NS_FILENAMES_PBOARD_TYPE);
    let has_file_url = names
        .iter()
        .any(|t| t == "public.file-url" || t == "NSFileURLPboardType");

    if !has_legacy && !has_file_url {
        return None;
    }

    if has_legacy {
        let pb = pasteboard();
        let key = NSString::from_str(NS_FILENAMES_PBOARD_TYPE);
        // `propertyListForType` hands back an untyped object, and `NSArray` is
        // downcastable only in its unparameterised form, so each element is
        // narrowed to `NSString` individually.
        let paths: Option<Vec<String>> = unsafe { pb.propertyListForType(&key) }
            .and_then(|plist| plist.downcast::<NSArray>().ok())
            .map(|array| {
                let mut out = Vec::with_capacity(array.count());
                for i in 0..array.count() {
                    if let Ok(string) = array.objectAtIndex(i).downcast::<NSString>() {
                        out.push(string.to_string());
                    }
                }
                out
            });
        if let Some(paths) = paths.filter(|p| !p.is_empty()) {
            return Some(paths);
        }
    }

    if has_file_url {
        // The file-url flavour holds a file URL, percent-encoded.
        if let Some(raw) = read_string(unsafe { NSPasteboardTypeFileURL }) {
            if let Some(path) = url_to_path(&raw) {
                return Some(vec![path]);
            }
        }
    }

    None
}

/// Turn a `file://` URL (or a bare path) into a filesystem path.
fn url_to_path(raw: &str) -> Option<String> {
    let trimmed = raw.trim();
    if trimmed.is_empty() {
        return None;
    }
    if !trimmed.starts_with("file:") {
        return Some(trimmed.to_string());
    }
    let after_scheme = trimmed.trim_start_matches("file://").trim_start_matches("file:");
    let decoded = percent_decode(after_scheme);
    if decoded.is_empty() {
        None
    } else {
        Some(decoded)
    }
}

fn percent_decode(input: &str) -> String {
    let bytes = input.as_bytes();
    let mut out: Vec<u8> = Vec::with_capacity(bytes.len());
    let mut i = 0;
    while i < bytes.len() {
        match bytes[i] {
            b'%' if i + 2 < bytes.len() => {
                let hex = std::str::from_utf8(&bytes[i + 1..i + 3]).ok();
                match hex.and_then(|h| u8::from_str_radix(h, 16).ok()) {
                    Some(byte) => {
                        out.push(byte);
                        i += 3;
                    }
                    None => {
                        out.push(b'%');
                        i += 1;
                    }
                }
            }
            byte => {
                out.push(byte);
                i += 1;
            }
        }
    }
    String::from_utf8_lossy(&out).into_owned()
}

fn read_image(names: &[String]) -> Option<Captured> {
    let has = |needle: &str| names.iter().any(|t| t == needle);

    if has("public.png") || has("NSPasteboardTypePNG") {
        if let Some(bytes) = read_data(unsafe { NSPasteboardTypePNG }) {
            if !bytes.is_empty() {
                return Some(Captured::Image {
                    bytes,
                    mime: "image/png",
                    ext: "png",
                });
            }
        }
    }

    if has("com.compuserve.gif") || has("public.gif") {
        // Read the raw GIF so animation survives; re-encoding would flatten it.
        let key = NSString::from_str("com.compuserve.gif");
        if let Some(bytes) = read_data(&key) {
            if !bytes.is_empty() {
                return Some(Captured::Image {
                    bytes,
                    mime: "image/gif",
                    ext: "gif",
                });
            }
        }
    }

    if has("public.tiff") || has("NSPasteboardTypeTIFF") {
        if let Some(tiff) = read_data(unsafe { NSPasteboardTypeTIFF }) {
            if !tiff.is_empty() {
                // Most apps refuse TIFF from the clipboard; store PNG instead.
                let (bytes, mime, ext) = match tiff_to_png(&tiff) {
                    Some(png) => (png, "image/png", "png"),
                    None => (tiff, "image/tiff", "tiff"),
                };
                return Some(Captured::Image { bytes, mime, ext });
            }
        }
    }

    None
}

fn tiff_to_png(tiff: &[u8]) -> Option<Vec<u8>> {
    use image::{ExtendedColorType, ImageEncoder};
    let img = image::load_from_memory_with_format(tiff, image::ImageFormat::Tiff)
        .or_else(|_| image::load_from_memory(tiff))
        .ok()?;
    let rgba = img.to_rgba8();
    let mut out = Vec::new();
    image::codecs::png::PngEncoder::new(&mut out)
        .write_image(
            rgba.as_raw(),
            rgba.width(),
            rgba.height(),
            ExtendedColorType::Rgba8,
        )
        .ok()?;
    Some(out)
}

/// Replace the pasteboard contents with one stacked item.
///
/// Callers must arm the self-write guard first (see `poller::arm_own_write`)
/// so this does not get recorded as a fresh copy.
pub fn write_item(item: &crate::types::ClipItem) -> Result<(), String> {
    let pb = pasteboard();
    unsafe { pb.clearContents() };

    match item.kind {
        crate::types::ClipKind::Text => {
            let text = item
                .text
                .as_deref()
                .ok_or_else(|| "that stacked text entry has no text".to_string())?;
            let ns = NSString::from_str(text);
            let ok = unsafe { pb.setString_forType(&ns, unsafe { NSPasteboardTypeString }) };
            if !ok {
                return Err("the system refused the text write".to_string());
            }
            if let Some(html) = &item.html {
                let data = NSData::from_vec(html.clone().into_bytes());
                unsafe { pb.setData_forType(Some(&data), unsafe { NSPasteboardTypeHTML }) };
            }
            if let Some(rtf_path) = &item.rtf_path {
                if let Ok(bytes) = std::fs::read(rtf_path) {
                    let data = NSData::from_vec(bytes);
                    unsafe { pb.setData_forType(Some(&data), unsafe { NSPasteboardTypeRTF }) };
                }
            }
            Ok(())
        }
        crate::types::ClipKind::Image => {
            let path = item
                .blob_path
                .as_deref()
                .ok_or_else(|| "that stacked image entry has no file".to_string())?;
            let bytes = std::fs::read(path)
                .map_err(|e| format!("could not read the stacked image: {e}"))?;
            let data = NSData::with_bytes(&bytes);
            let mime = item.mime.as_deref().unwrap_or("image/png");
            let primary = if mime == "image/tiff" {
                unsafe { NSPasteboardTypeTIFF }
            } else {
                unsafe { NSPasteboardTypePNG }
            };
            let ok = unsafe { pb.setData_forType(Some(&data), primary) };
            if !ok {
                return Err("the system refused the image write".to_string());
            }
            // Also offer TIFF: older apps only advertise that flavour.
            if mime != "image/tiff" {
                if let Some(tiff) = png_to_tiff(&bytes) {
                    let tiff_data = NSData::with_bytes(&tiff);
                    unsafe { pb.setData_forType(Some(&tiff_data), unsafe { NSPasteboardTypeTIFF }) };
                }
            }
            Ok(())
        }
        crate::types::ClipKind::Files => {
            if item.file_urls.is_empty() {
                return Err("that stacked entry has no files".to_string());
            }
            let mut objects: Vec<objc2::rc::Retained<
                objc2::runtime::ProtocolObject<dyn objc2_app_kit::NSPasteboardWriting>,
            >> = Vec::with_capacity(item.file_urls.len());
            for path in &item.file_urls {
                let ns_path = NSString::from_str(path);
                let url = unsafe { objc2_foundation::NSURL::fileURLWithPath(&ns_path) };
                objects.push(objc2::runtime::ProtocolObject::from_retained(url));
            }
            let array = NSArray::from_retained_slice(&objects);
            let ok = unsafe { pb.writeObjects(&array) };
            if ok {
                Ok(())
            } else {
                Err("the system refused the file write".to_string())
            }
        }
    }
}

fn png_to_tiff(bytes: &[u8]) -> Option<Vec<u8>> {
    use image::{ExtendedColorType, ImageEncoder};
    let img = image::load_from_memory(bytes).ok()?;
    let rgba = img.to_rgba8();
    // The TIFF encoder writes with random access, so it needs `Seek`, which a
    // bare `Vec` does not implement.
    let mut out = std::io::Cursor::new(Vec::new());
    image::codecs::tiff::TiffEncoder::new(&mut out)
        .write_image(
            rgba.as_raw(),
            rgba.width(),
            rgba.height(),
            ExtendedColorType::Rgba8,
        )
        .ok()?;
    Some(out.into_inner())
}

/// Put a plain string on the pasteboard without any history bookkeeping.
pub fn write_plain_text(text: &str) -> Result<(), String> {
    let pb = pasteboard();
    unsafe { pb.clearContents() };
    let ns = NSString::from_str(text);
    let ok = unsafe { pb.setString_forType(&ns, unsafe { NSPasteboardTypeString }) };
    if ok {
        Ok(())
    } else {
        Err("the system refused the text write".to_string())
    }
}
